dist: trusty

sudo: false

language: c

cache: ccache

compiler:
  - gcc

addons:
  apt:
    packages:
      - binutils-dev
      - liblzma-dev
      - syslinux
      - genisoimage

env:
  global:
  - MAKEFLAGS="-j 4"
  - src_lldp_c='src/net/lldp.c'
  - src_lldp_h='src/include/ipxe/lldp.h'
  - bios_binary_dir='bin'
  - bios_binary_file='undionly.kkpxe'
  - binary="${bios_binary_dir}/${bios_binary_file}"
 
script:
  - git clone https://git.ipxe.org/ipxe.git
  - mv $src_lldp_c ipxe/$src_lldp_c
  - mv $src_lldp_h ipxe/$src_lldp_h
  - sh patch.sh
  - pwd
  - cd ipxe/src && make $binary

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name 'travis-ci'
      - git config --local user.email "ipxe.tannevaled@travis-ci.org"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: XaJC+0d2zSbdBueA+CrJWhK6KlAuAXfpzniulJ7G2dcsVn+FaKbPTmocfw1N6WsKTAB+WIIQjpoNHtD+P1gQNBjrLPPV8BPAAICqTXV1csZfnzOd+xH36GzCt5IPsJvBuZq6NcPtTUYalXYIWYKvJ27ddjWgsGpYzRWvKfwf1JzvB0QBZzGfhr7uTRKwuhgMde3DLD1n3AZAj2AhmE4//USwKXLaFkN81hR08Fi7MAWZaKNQOL9hb81aphIoXyYSkuTbHEH0fUu63kuZzyhzrMGMooLBNCsw9nH8z143czSqcyr8PsHMd3/NGsPNOI5XUlBwO5GuT3luQmO0cvo0sQQFe4TTqH6ZvwAxWF/9u5wpomKXJHVXompvmber4fDLn35YfCHo8GYq8cNZdgtW6ag4G/tWziIaIcSI42aSlQpyM+8Fg4SbTCMojBz0rfFucCSrR/ZsXdSAPX/1UUuHhSRJKPZz8WY1H60xLjETe7gexw/O4DeG7ciKeyQwA8yaT1aQK1+1ahl2qq/hzFFfIVdUSbyBUZaGrtVrVNL5susk+/1vZlvtVpL2IopKUPgpqX1jbJv+jYZ3eCAqgc9lfRFZH/eRuwp3Fe7u8Fz8jnKP0wEo/KyXc0S6XpU+Jt5hXP+ReBvGaXVfmsb5oVk1K6cHsaZ+19Q6BBCnLxc7p/c=
  file: ipxe/src/$binary
  on:
    repo: tannevaled/ipxe
  skip_cleanup: true
